<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="actitimeSuite" duration-ms="83189" started-at="2020-06-10T11:29:07Z" finished-at="2020-06-10T11:30:31Z">
    <groups>
    </groups>
    <test name="finalProject" duration-ms="83189" started-at="2020-06-10T11:29:07Z" finished-at="2020-06-10T11:30:31Z">
      <class name="com.test.ValidLogin">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.test.ValidLogin@48140564]" name="openBrowser" is-config="true" duration-ms="24313" started-at="2020-06-10T17:00:02Z" finished-at="2020-06-10T17:00:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="PASS" signature="loginPage()[pri:0, instance:com.test.ValidLogin@48140564]" name="loginPage" duration-ms="3205" started-at="2020-06-10T17:00:27Z" finished-at="2020-06-10T17:00:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPage -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.test.ValidLogin@48140564]" name="tearDown" is-config="true" duration-ms="703" started-at="2020-06-10T17:00:30Z" finished-at="2020-06-10T17:00:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.test.ValidLogin -->
      <class name="com.test.InvalidLogin">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.test.InvalidLogin@3cb5cdba]" name="openBrowser" is-config="true" duration-ms="37967" started-at="2020-06-10T16:59:08Z" finished-at="2020-06-10T16:59:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="FAIL" signature="loginPage()[pri:0, instance:com.test.InvalidLogin@3cb5cdba]" name="loginPage" duration-ms="16010" started-at="2020-06-10T16:59:46Z" finished-at="2020-06-10T17:00:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[success expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: success expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at com.test.InvalidLogin.loginPage(InvalidLogin.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPage -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.test.InvalidLogin@3cb5cdba]" name="tearDown" is-config="true" duration-ms="883" started-at="2020-06-10T17:00:02Z" finished-at="2020-06-10T17:00:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.test.InvalidLogin -->
    </test> <!-- finalProject -->
  </suite> <!-- actitimeSuite -->
</testng-results>
